name: Publish MCP Server to GitHub Container Registry

on:
  # Runs on pushes with a version attached to it
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - uses: actions/checkout@v6

      - name: Normalize image name
        run: echo "IMAGE=${IMAGE,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE }}:${{ github.ref_name }}
            ${{ env.IMAGE }}:latest
          labels: |
            io.modelcontextprotocol.server.name="io.github.${{ env.IMAGE }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
